services:
  db:
    image: postgres:17
    container_name: dev-postgres
    environment:
      POSTGRES_USER: sax
      POSTGRES_PASSWORD: saxpw
      POSTGRES_DB: balances
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
